INSERT INTO web_pages (url, title, description, content) VALUES
('https://www.example.com/spaghetti-carbonara', 'Spaghetti Carbonara', 'Classic Italian pasta dish', 'Spaghetti carbonara is a classic Roman pasta dish made with eggs, cheese, bacon (pancetta), and black pepper. It is creamy, rich, and satisfying.'),
('https://www.example.com/chicken-tikka-masala', 'Chicken Tikka Masala', 'Popular Indian curry dish', 'Chicken tikka masala is a popular Indian curry dish made with marinated and grilled chicken pieces simmered in a spiced tomato-based sauce. It is often served with rice or naan bread.'),
('https://www.example.com/caesar-salad', 'Caesar Salad', 'Classic salad with Caesar dressing', 'Caesar salad is a classic salad made with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing. It is a refreshing and delicious dish that can be served as a side or a main course.'),
('https://www.example.com/pad-thai', 'Pad Thai', 'Traditional Thai stir-fried noodle dish', 'Pad Thai is a popular Thai dish made with stir-fried rice noodles, eggs, tofu or shrimp, bean sprouts, peanuts, and a tangy tamarind sauce. It is commonly garnished with lime wedges and cilantro.'),
('https://www.example.com/beef-stroganoff', 'Beef Stroganoff', 'Comfort food classic', 'Beef stroganoff is a classic Russian dish made with sautéed beef strips, mushrooms, onions, and sour cream sauce. It is typically served over egg noodles or rice.'),
('https://www.example.com/margherita-pizza', 'Margherita Pizza', 'Classic Italian pizza', 'Margherita pizza is a classic Italian pizza topped with tomato sauce, fresh mozzarella cheese, basil leaves, and a drizzle of olive oil. It is a simple yet delicious pizza that showcases the flavors of its ingredients.'),
('https://www.example.com/chocolate-chip-cookies', 'Chocolate Chip Cookies', 'Homemade cookie favorite', 'Chocolate chip cookies are a beloved homemade treat made with butter, sugar, flour, chocolate chips, and vanilla extract. They are soft, chewy, and packed with chocolatey goodness.'),
('https://www.example.com/guacamole', 'Guacamole', 'Classic Mexican dip', 'Guacamole is a classic Mexican dip made with ripe avocados, onions, tomatoes, cilantro, lime juice, and salt. It is creamy, flavorful, and perfect for dipping tortilla chips or spreading on tacos and sandwiches.'),
('https://www.example.com/chocolate-cake', 'Chocolate Cake', 'Decadent dessert favorite', 'Chocolate cake is a decadent dessert made with cocoa powder, flour, sugar, eggs, butter, and milk. It is rich, moist, and chocolatey, often topped with frosting or ganache for added indulgence.'),
('https://www.example.com/greek-salad', 'Greek Salad', 'Healthy and flavorful salad', 'Greek salad is a healthy and flavorful salad made with fresh tomatoes, cucumbers, red onions, bell peppers, olives, feta cheese, and a dressing of olive oil, lemon juice, garlic, and herbs.');
